### ISSUE TITLE
fix naming

### ISSUE THREAD

**Issue by paultag** [paultag/go-debian#28]
I hate the `FooFile` convention we've grown. Ideas? cc @tianon

**Comment by tianon** [comment]
Yeah, I'm not sure.  I love the functions because they keep my code clean of `os.Open` calls, but more importantly the way they're scoped makes sure that the `defer f.Close()` runs at a nice early point (before my code even gets the results back), which wouldn't be true of me dropping this same boiler in my own code.

It's also fairly consistent with the stdlib (including the naming): https://golang.org/pkg/text/template/#Template.Parse vs https://golang.org/pkg/text/template/#Template.ParseFiles for example.

**Comment by paultag** [comment]
Good enough for the stdlib good enough for me
